from pyswip import Prolog
import tempfile
import os
from pyswip.prolog import PrologError

prolog = Prolog()


def run_fuzzy_prolog(program: str=None, query: str=None):
    if not program or not query:
        return {
            "engine": "fuzzy_swi",
            "error": "invalid_input",
            "message": "Program or query is missing."
        }

    prolog.consult("fuzzy_core.pl")

    with tempfile.NamedTemporaryFile(mode="w", suffix=".pl", delete=False) as f:
        f.write(program)
        temp_file = f.name

    try:
        prolog.consult(temp_file)
        results = list(prolog.query(query))

        return {
            "engine": "fuzzy_swi",
            "results": results
        }

    except PrologError as e:
        return {
            "engine": "fuzzy_swi",
            "error": "prolog_runtime_error",
            "message": str(e),
            "program": program,
            "query": query
        }

    finally:
        os.remove(temp_file)




def run_crisp_prolog(program: str=None, query: str=None):
    if not program or not query:
        return {
            "engine": "crisp_prolog",
            "error": "invalid_input",
            "message": "Program or query is missing."
        }

    with tempfile.NamedTemporaryFile(mode="w", suffix=".pl", delete=False) as f:
        f.write(program)
        temp_file = f.name

    try:
        prolog.consult(temp_file)
        results = list(prolog.query(query))

        return {
            "engine": "crisp_prolog",
            "results": results
        }

    except PrologError as e:
        return {
            "engine": "crisp_prolog",
            "error": "prolog_runtime_error",
            "message": str(e),
            "program": program,
            "query": query
        }

    finally:
        os.remove(temp_file)




# JSON schema definitions for LLM tool calling

TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "run_crisp_prolog",
            "description": (
                "Executes a crisp Prolog program generated by the LLM. "
                "Returns results as a list of dictionaries. "
                "No fuzzy core is loaded."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "program": {
                        "type": "string",
                        "description": "LLM-generated Prolog rules and facts as a string."
                    },
                    "query": {
                        "type": "string",
                        "description": "Prolog query to run, e.g., 'good_player(john).'"
                    }
                },
                "required": ["program", "query"],
                "additionalProperties": False
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "run_fuzzy_prolog",
            "description": (
                "Executes a fuzzy Prolog program using fuzzy_core.pl. "
                "Returns results including truth values."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "program": {
                        "type": "string",
                        "description": "LLM-generated fuzzy Prolog rules and facts as a string."
                    },
                    "query": {
                        "type": "string",
                        "description": "Fuzzy Prolog query to run, e.g., 'good_player(john, T)'."
                    }
                },
                "required": ["program", "query"],
                "additionalProperties": False
            }
        }
    }
]

